Repository aws/mynah-ui, pull requests merged in 2024-11, with the labels that each got.

#157 Fix disappearing span tags inside code blocks
  src/components/__test__/syntax-highlighter.spec.ts
  src/components/button.ts
  src/components/card/card-body.ts
  src/components/syntax-highlighter.ts
  src/styles/components/card/_card-body.scss
  src/styles/components/chat/_chat-item-card.scss
Labels: bug

#161 Updated PR runner to use MacOS-latest
  .github/workflows/new_pr.yml
  ui-tests/__test__/flows/welcome-mode.ts
Labels: enhancement

#162 Also updated publish action script to use MacOS-latest
  .github/workflows/publish.yml
Labels: enhancement

#164 163 quick action commands confirmation
  docs/CONFIG.md
  docs/img/texts/commandConfirmation.png
  src/components/chat-item/chat-prompt-input.ts
  src/components/chat-item/prompt-input/prompt-text-input.ts
  src/helper/config.ts
  src/static.ts
Labels: enhancement

#167 Jurredr/add quick command e2e tests
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-context-selector-should-close-the-context-selector-by-clicking-outside-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-context-selector-should-close-the-context-selector-by-pressing-escape-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-context-selector-should-filter-context-selector-list-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-context-selector-should-render-the-context-selector-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-context-selector-should-select-context-selector-item-by-clicking-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-context-selector-should-select-context-selector-item-through-buttons-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-context-selector-should-select-context-selector-item-with-enter-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-context-selector-should-select-context-selector-item-with-space-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-context-selector-should-select-context-selector-item-with-tab-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-quick-command-selector-should-close-the-quick-command-selector-by-blur-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-quick-command-selector-should-close-the-quick-command-selector-by-clicking-outside-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-quick-command-selector-should-close-the-quick-command-selector-by-pressing-escape-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-quick-command-selector-should-filter-quick-command-selector-list-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-quick-command-selector-should-render-the-quick-command-selector-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-quick-command-selector-should-select-quick-command-selector-item-by-clicking-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-quick-command-selector-should-select-quick-command-selector-item-through-buttons-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-quick-command-selector-should-select-quick-command-selector-item-with-enter-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-quick-command-selector-should-select-quick-command-selector-item-with-space-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-quick-command-selector-should-select-quick-command-selector-item-with-tab-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-context-selector-should-close-the-context-selector-by-clicking-outside-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-context-selector-should-close-the-context-selector-by-pressing-escape-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-context-selector-should-filter-context-selector-list-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-context-selector-should-render-the-context-selector-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-context-selector-should-select-context-selector-item-by-clicking-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-context-selector-should-select-context-selector-item-through-buttons-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-context-selector-should-select-context-selector-item-with-enter-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-context-selector-should-select-context-selector-item-with-space-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-context-selector-should-select-context-selector-item-with-tab-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-quick-command-selector-should-close-the-quick-command-selector-by-blur-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-quick-command-selector-should-close-the-quick-command-selector-by-clicking-outside-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-quick-command-selector-should-close-the-quick-command-selector-by-pressing-escape-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-quick-command-selector-should-filter-quick-command-selector-list-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-quick-command-selector-should-render-the-quick-command-selector-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-quick-command-selector-should-select-quick-command-selector-item-by-clicking-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-quick-command-selector-should-select-quick-command-selector-item-through-buttons-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-quick-command-selector-should-select-quick-command-selector-item-with-enter-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-quick-command-selector-should-select-quick-command-selector-item-with-space-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-quick-command-selector-should-select-quick-command-selector-item-with-tab-1-snap.png
  ui-tests/__test__/flows/quick-picks/close-quick-picks.ts
  ui-tests/__test__/flows/quick-picks/filter-quick-picks.ts
  ui-tests/__test__/flows/quick-picks/render-quick-picks.ts
  ui-tests/__test__/flows/quick-picks/select-quick-picks.ts
  ui-tests/__test__/main.spec.ts
  ui-tests/src/defaults.ts
  ui-tests/src/mocks/mock-data.ts
Labels: enhancement

#172 Extended tabbed card E2E test by switching tabs
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-should-render-tabbed-cards-correctly-2-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-should-render-tabbed-cards-correctly-2-snap.png
  ui-tests/__test__/flows/render-tabbed-card.ts
Labels: testing

#174 [improvement] Fixed GitHub issue template labels, added improvement issue template
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/guidance_request.md
  .github/ISSUE_TEMPLATE/improvement.md
Labels: improvement

#176 [improvement] better syntax highlighting
  src/styles/_variables.scss
  src/styles/components/_syntax-highlighter.scss
Labels: improvement

#171 Jurredr/update button colors
  example/src/commands.ts
  example/src/main.ts
  example/src/samples/sample-data.ts
  package-lock.json
  package.json
  src/styles/components/_button.scss
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-should-render-buttons-on-cards-correctly-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-should-render-buttons-on-cards-correctly-2-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-should-render-buttons-on-cards-correctly-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-should-render-buttons-on-cards-correctly-2-snap.png
Labels: new feature

#183 [improvement] consider hiding cursor in prompt input during command confirmation
  src/components/chat-item/chat-prompt-input.ts
  src/styles/components/chat/_chat-prompt-wrapper.scss
Labels: improvement

#179 [bug] buttons render in reverse order
  postinstall.js
  src/static.ts
  src/styles/components/_form-input.scss
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-should-render-buttons-on-cards-correctly-2-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-should-render-buttons-on-cards-correctly-2-snap.png
Labels: bug

#189 Add E2E tests for forms
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-forms-should-disable-forms-on-submit-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-forms-should-remove-form-card-when-canceled-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-forms-should-render-form-elements-correctly-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-should-render-buttons-on-cards-correctly-2-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-tabs-should-close-the-tab-1-snap.png
  ui-tests/__test__/__image_snapshots__/chromium/main-spec-ts-open-mynah-ui-tabs-should-open-a-new-the-tab-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-forms-should-disable-forms-on-submit-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-forms-should-remove-form-card-when-canceled-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-forms-should-render-form-elements-correctly-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-should-close-the-tab-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-should-open-a-new-the-tab-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-should-render-buttons-on-cards-correctly-2-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-tabs-should-close-the-tab-1-snap.png
  ui-tests/__test__/__image_snapshots__/webkit/main-spec-ts-open-mynah-ui-tabs-should-open-a-new-the-tab-1-snap.png
  ui-tests/__test__/flows/form/disable-form.ts
  ui-tests/__test__/flows/form/remove-form.ts
  ui-tests/__test__/flows/form/render-form-elements.ts
  ui-tests/__test__/main.spec.ts
Labels: testing

#190 Extended new PR GitHub workflow to send notification to Slack channel
  .github/workflows/new_pr.yml
Labels: improvement

#194 Added repository name to Slack PR webhook payload
  .github/workflows/new_pr.yml
Labels: improvement
